# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://joelkhoo.github.io
title: joelkhoo.github.io
email: joelkhoo@gmail.com
author: Joel Khoo
description: > # "Joel Khoo is a full stack developer with an interest in machine learning and the blockchain.
copyright: 'Copyright &copy; 2017 Joel Khoo. All Rights Reserved.'
credits: 'Code is Law'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://joelkhoo.github.io
  - title: linkedin
    url: https://www.linkedin.com/in/joelkhoo/
  - title: angellist
    url: https://angel.co/joel-khoo
